name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run CI tests
        run: |
          # Replace this command with your CI test commands
          echo "Running CI tests..."
          python

  cd:
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t subhaganesh/stud_perfo_app:latest .

      - name: Push Docker image to Docker Hub
        run: docker push subhaganesh/stud_perfo_app:latest

  deploy:
    needs: cd
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Production
        run: |
          # Replace the following commands with your deployment steps
            echo "Deploying the Docker image to production..."
            ssh subhaganesh@192.168.43.1 "docker pull subhaganesh/stud_perfo_app:latest && docker stop vigilant_carver && docker rm vigilant_carver && docker run -d --name vigilant_carver -p 5000:5000 subhaganesh/stud_perfo_app:latest"
