name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run CI tests
        run: |
          # Replace this command with your CI test commands
          echo "Running CI tests..."
          python

  cd:
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t subhaganesh/stud_perfo_app:latest .

      - name: Push Docker image to Docker Hub
        run: docker push subhaganesh/stud_perfo_app:latest

  deploy:
    needs: cd
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Production
        run: |
          # Replace the following commands with your deployment steps
            echo "Deploying the Docker image to production..."
<<<<<<< HEAD
            ssh subhaganesh@192.168.43.1 "docker pull subhaganesh/stud_perfo_app:latest && docker stop vigilant_carver && docker rm aa2f99e6f215 && docker run -d --name aa2f99e6f215 -p 0.0.0.0:5000 subhaganesh/stud_perfo_app:latest"
=======
            ssh subhaganesh@192.168.43.1 "docker pull subhaganesh/stud_perfo_app:latest && docker stop vigilant_carver && docker rm aa2f99e6f215 && docker run -d --name aa2f99e6f215 -p 0.0.0.0:5000 subhaganesh/stud_perfo_app:latest"
>>>>>>> 491f376fbe2aac8ab72dba121e2d0241186b811c
